server:
  port: 18023
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-0h1jm6m4.sql.tencentcdb.com:21955/socialContactApp
    username: root
    password: lyx66daA@
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
      time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.hmdp: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  table:
    auto=update: update
    mybatis:
      database:
        type: mysql
  mybatis:
    model:
      pack: com.example.socialcontactapp.entity